// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAScB_B5rrduscyNDp3_ePUh0agsagyoik',
    appId: '1:183026198702:web:8442a241640e43e36b253f',
    messagingSenderId: '183026198702',
    projectId: 'kucingku-hilang',
    authDomain: 'kucingku-hilang.firebaseapp.com',
    storageBucket: 'kucingku-hilang.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkCawwuUMaTgJ3pT_y2dj-vZnoZY8D8Go',
    appId: '1:183026198702:android:ef2b8d9ee4457d176b253f',
    messagingSenderId: '183026198702',
    projectId: 'kucingku-hilang',
    storageBucket: 'kucingku-hilang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBExq3cjZtLA7GwtWWVivk8_FhEwhzwxdc',
    appId: '1:183026198702:ios:8979b5f4ce83f44e6b253f',
    messagingSenderId: '183026198702',
    projectId: 'kucingku-hilang',
    storageBucket: 'kucingku-hilang.appspot.com',
    iosClientId: '183026198702-fqrga09p6ttgn7r8lpiji80fs8ktjoqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.kucingkuHilang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBExq3cjZtLA7GwtWWVivk8_FhEwhzwxdc',
    appId: '1:183026198702:ios:8979b5f4ce83f44e6b253f',
    messagingSenderId: '183026198702',
    projectId: 'kucingku-hilang',
    storageBucket: 'kucingku-hilang.appspot.com',
    iosClientId: '183026198702-fqrga09p6ttgn7r8lpiji80fs8ktjoqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.kucingkuHilang',
  );
}
